!munch.Munch
train_datasets: ['4d_ellipsoids']
4d: True
num_time_points: 8

work_dir: experiments/
batch_size: 1
model_name: point2ssm++_4d
encoder: pstnet2
device: cuda:0
mapping_error_weight: 0.1
cd_loss: cd_l2

consistency_start_epoch: 0
sampling_invariance: True
rotation_equivarince: True
consistency_loss_weight: 1
consistency_rotation_range: 15

num_input_points: 128
latent_dim: 128
dgcnn_k: 27
num_output_points: 128

missing_percent: null     # 0.05, 0.1, 0.2
train_subset_size: null   # 6, 12, 25, 50, 100
noise_level: null         # 0.25, 0.5, 1, 2
rot_range: null

nepoch: 3000
early_stop: True
early_stop_patience: 100
early_stop_start: 0

optimizer: Adam
betas: 0.9, 0.999
lr: 0.0001
lr_decay: False

manual_seed: null
weight_decay: 0
workers: 0

epoch_interval_to_save: 10
epoch_interval_to_val: 1
step_interval_to_print: 400

save_predictions: true

load_model: null
start_epoch: 0
scale: False
log_metrics: ['loss', 'base_loss', 'consist_loss', 'cd_l1', 'cd_l2', 'mapping_error']